import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Path to your CSV file generated by the shell script
csv_file = 'experiment_results.csv'

# Read CSV into pandas DataFrame
df = pd.read_csv(csv_file)

# Function to plot average visited nodes as a function of 'n'


def plot_avg_visited_nodes(df, tree_type):
    avg_visited_nodes = df.groupby('n')['Average visited nodes'].mean()
    plt.figure(figsize=(10, 6))
    plt.plot(avg_visited_nodes.index, avg_visited_nodes.values,
             marker='o', linestyle='-')
    plt.title(f'Average Cost of Partial Match Queries as a Function of n for {
              tree_type} k-d Tree')
    plt.xlabel('n')
    plt.ylabel('Average visited nodes')
    plt.grid(True)
    plt.tight_layout()
    plt.savefig(f'{tree_type}_average_cost_vs_n.png')
    plt.show()

# Function to plot average visited nodes varying 'k' and 's' in subplots


def plot_avg_visited_nodes_varying_k(df, tree_type):
    plt.figure(figsize=(16, 10))
    # Plot for varying 'k'
    sns.lineplot(data=df, x='k', y='Average visited nodes',
                 hue='s', marker='o', palette='colorblind')
    plt.title(f'Average Visited Nodes for {tree_type} k-d Tree (Varying k)')
    plt.xlabel('k')
    plt.ylabel('Average visited nodes')
    plt.grid(True)
    # Additional customization for layout
    plt.tight_layout()
    plt.savefig(f'{tree_type}_average_visited_nodes_varying_k.png')
    plt.show()


def plot_avg_visited_nodes_varying_s(df, tree_type):
    plt.figure(figsize=(16, 10))
    # Plot for varying 's'
    sns.lineplot(data=df, x='s', y='Average visited nodes',
                 hue='k', marker='o', palette='colorblind')
    plt.title(f'Average Visited Nodes for {tree_type} k-d Tree (Varying s)')
    plt.xlabel('s')
    plt.ylabel('Average visited nodes')
    plt.grid(True)

    # Additional customization for layout
    plt.tight_layout()
    plt.savefig(f'{tree_type}_average_visited_nodes_varying_s.png')
    plt.show()


# Loop through each type and generate plots
for tree_type in ['standard', 'relaxed']:
    df_filtered = df[df['type'] == tree_type]
    plot_avg_visited_nodes(df_filtered, tree_type)
    plot_avg_visited_nodes_varying_s(df_filtered, tree_type)
    plot_avg_visited_nodes_varying_k(df_filtered, tree_type)
