import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns


def alpha_x(x):
    return (np.sqrt(9 - 8*x) / 2) + x - 1.5


def alpha(s, K):
    x = s / K
    return 1 - x + alpha_x(x)


# Path to your CSV file generated by the shell script
csv_file = 'experiment_results.csv'

# Read CSV into pandas DataFrame
df = pd.read_csv(csv_file)

# Filter only rows where type is 'relaxed'
df_relaxed = df[df['type'] == 'relaxed']

# Extract relevant columns from the DataFrame
n_exp = df_relaxed['n']  # Number of points
avg_visited_nodes_exp = df_relaxed['Average visited nodes']

# Define specific values for s and K
s_values = [1, 2, 3, 4, 5]
K = 10

# Define the range of n for theoretical plot
n_theoretical = np.linspace(1, 20000, 500)

# Set up Seaborn style
sns.set(style='whitegrid', palette='deep', font_scale=1.2)

# Plotting
plt.figure(figsize=(10, 6))

# Theoretical plots
for s in s_values:
    alpha_value = alpha(s, K)
    cost = n_theoretical ** alpha_value
    plt.plot(n_theoretical, cost, linestyle='-', linewidth=2,
             label=f'Theoretical: s={s}, alpha={alpha_value:.2f}')

# Experimental data
plt.scatter(n_exp, avg_visited_nodes_exp, color='red',
            label='Experimental Data', marker='o', s=50, alpha=0.8)

plt.xlabel('n (Number of points)', fontsize=12)
plt.ylabel('Average Visited Nodes', fontsize=12)
plt.title('Theoretical vs. Experimental Average Visited Nodes', fontsize=14)
plt.legend(fontsize=10)
plt.yscale('log')  # Using log scale for better visualization
plt.grid(True, which='both', linestyle='--', linewidth=0.5)
plt.tick_params(axis='both', which='major', labelsize=10)

# Adjust layout to prevent clipping of labels
plt.tight_layout()

# Save the plot as a PNG file
plt.savefig('theoretical_vs_experimental_seaborn.png', dpi=300)

# Show the plot
plt.show()
